// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irgssotfjgfunpbasfbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZ3Nzb3RmamdmdW5wYmFzZmJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzA3MjYsImV4cCI6MjA2NDQ0NjcyNn0._CXFtieoWrH2JFQTkOXVHKqA2uMNbb8m-FCdrnTTjFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);